on: [push]
name: Docs & Demo
jobs:
#  docs:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Build
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: phpdocumentor/phpdocumentor/docs.phpdoc.org
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          context: docs
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'deploy'
        uses: ./.github/actions/docker-deploy # use this repo as an action
        with:
          image: 'phpdoc/docs.phpdoc.org'
          tag: '3.0'
#    steps:

#      - name: 'phpDoc clean'
#        uses: ./ # use this repo as an action
#        with:
#          template: 'clean'
#          target: 'build/clean'
#      - name: 'phpDoc default'
#        uses: ./ # use this repo as an action
#        with:
#          template: 'default'
#          target: 'build/default'
#      - name: 'Fix file permissions'
#        run: 'sudo chown $USER ./build'
#      - name: 'Copy docker files'
#        run: 'cp ./data/demo/* ./build'
#      - name: Build
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: phpdocumentor/phpdocumentor/demo.phpdoc.org
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          context: build

